### ISSUE TITLE
Request: let macro indent things a bit!

### ISSUE THREAD

**Issue by Trevoke** [DarwinAwardWinner/with-simulated-input#19]
If you add `  (declare (indent 2))` to the beginning of the macro it will tell the emacs editor to indent two spaces (you can use 4, 7, whatever) anything in the block and I find it more readable. :D

**Comment by DarwinAwardWinner** [comment]
The N in `(declare (indent N))` does not determine the number of spaces to indent, it determines the number of *arguments* to indent specially. `with-simulated-input` already [declares `(indent 1)`](https://github.com/DarwinAwardWinner/with-simulated-input/blob/master/with-simulated-input.el#L306) since only the first argument is different from the rest.
